<?php
/*
 * Connexion à distance : fichier .rdp des manuels de maintenance (RDS du cégep).
 * Servi uniquement aux comptes connectés ayant la permission « distant » (ou admin),
 * jamais au compte invité.
 */
define('_FVEILLEUX', 1);
require_once __DIR__ . '/session.php';

$s = getSession();
if (!$s) { http_response_code(401); header('Content-Type: text/plain; charset=utf-8'); exit('Connexion requise.'); }
$perms = is_array($s['permissions'] ?? null) ? $s['permissions'] : [];
if (($s['role'] ?? '') === 'guest' || (($s['role'] ?? '') !== 'admin' && !in_array('distant', $perms, true))) {
  http_response_code(403); header('Content-Type: text/plain; charset=utf-8'); exit('Accès refusé.');
}

$rdp = <<<'RDP'
redirectclipboard:i:1
redirectprinters:i:1
redirectcomports:i:0
redirectsmartcards:i:0
devicestoredirect:s:*
drivestoredirect:s:C:\;Z:\
session bpp:i:32
prompt for credentials on client:i:1
server port:i:3389
allow font smoothing:i:1
promptcredentialonce:i:1
videoplaybackmode:i:1
audiocapturemode:i:1
gatewayusagemethod:i:2
gatewayprofileusagemethod:i:1
gatewaycredentialssource:i:0
full address:s:ED5RDSBRK.LABORATOIRE.COLLEGEEM.QC.CA
gatewayhostname:s:rds.cegepmontpetit.ca
workspace id:s:ED5RDSBRK.laboratoire.collegeem.qc.ca
use redirection server name:i:1
loadbalanceinfo:s:tsv://MS Terminal Services Plugin.1.MANUELS
use multimon:i:1
alternate full address:s:ED5RDSBRK.LABORATOIRE.COLLEGEEM.QC.CA
signscope:s:Full Address,Alternate Full Address,Use Redirection Server Name,Server Port,GatewayHostname,GatewayUsageMethod,GatewayProfileUsageMethod,GatewayCredentialsSource,PromptCredentialOnce,RedirectPrinters,RedirectCOMPorts,RedirectSmartCards,RedirectClipboard,DevicesToRedirect,DrivesToRedirect,LoadBalanceInfo
signature:s:AQABAAEAAACQEQAAMIIRjAYJKoZIhvcNAQcCoIIRfTCCEXkCAQExDzANBglghkgB  ZQMEAgEFADALBgkqhkiG9w0BBwGggg9jMIIDxTCCAq2gAwIBAgIBADANBgkqhkiG  9w0BAQsFADCBgzELMAkGA1UEBhMCVVMxEDAOBgNVBAgTB0FyaXpvbmExEzARBgNV  BAcTClNjb3R0c2RhbGUxGjAYBgNVBAoTEUdvRGFkZHkuY29tLCBJbmMuMTEwLwYD  VQQDEyhHbyBEYWRkeSBSb290IENlcnRpZmljYXRlIEF1dGhvcml0eSAtIEcyMB4X  DTA5MDkwMTAwMDAwMFoXDTM3MTIzMTIzNTk1OVowgYMxCzAJBgNVBAYTAlVTMRAw  DgYDVQQIEwdBcml6b25hMRMwEQYDVQQHEwpTY290dHNkYWxlMRowGAYDVQQKExFH  b0RhZGR5LmNvbSwgSW5jLjExMC8GA1UEAxMoR28gRGFkZHkgUm9vdCBDZXJ0aWZp  Y2F0ZSBBdXRob3JpdHkgLSBHMjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC  ggEBAL9xYgjx+lk09xvJGKP3gElY6SKDE6bFIEMBO4Tx5oVJnyfq9oQbTqC023CY  xzIBsQU+B07u9PpPL1kwIuerGVZr4oAH/PMWdYA5UXvl+TW2dE6pjYIT5LY/qQOD  +qK+ihVqf94Lw7YZFAXK6sOoBJQ7RnwyDfMAZiLIjWltNowRGLfTshxgtDj6AozO  091GB94KPutdfMh8+7ArU6SSYmlRJQVhGkSBjCypQ5Yj36w6gZoOKcUcqeldHrae  njAKOc7xiID7S13MMuyFYkMlNAJWJwGRtDtwKj9useiciAF9n9T521NtYJ2/LOdY  q7hfRvzOxBsDPAnrSTFcaUaz4EcCAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAO  BgNVHQ8BAf8EBAMCAQYwHQYDVR0OBBYEFDqahQcQZyi27/a9BUFuIMGU2g/eMA0G  CSqGSIb3DQEBCwUAA4IBAQCZ21151fmXWWcDYfF+OwYxdS2hII5PZYe096acvNjp  L9DbWu7PdIxztDhC2gV7+AJ1uP2lsdeu9tfeE8tTEH6KRtGX+rcuKxGrkLAngPno  n1rpN5+r5N9ss4UXnT3ZJE95kTXWXwTrgIOrmgIttRD02JDHBHNA7XIloKmf7J6r  aBKZV8aPEjoJpL1E/QYVN8Gb5DKj7Tjo2GTzLH4U/ALqn83/B2gX2yKQOC16jdFU  8WnjXzPKej17CuPKf1855eJ1usV2GDPOLPAvTK33sefOT6jEm0pUBsV/fdUID+Ic  /n4XuKxe9tQWskMJDE32p2u0mYRlynqI4uJEvlz36hz1MIIE0DCCA7igAwIBAgIB  BzANBgkqhkiG9w0BAQsFADCBgzELMAkGA1UEBhMCVVMxEDAOBgNVBAgTB0FyaXpv  bmExEzARBgNVBAcTClNjb3R0c2RhbGUxGjAYBgNVBAoTEUdvRGFkZHkuY29tLCBJ  bmMuMTEwLwYDVQQDEyhHbyBEYWRkeSBSb290IENlcnRpZmljYXRlIEF1dGhvcml0  eSAtIEcyMB4XDTExMDUwMzA3MDAwMFoXDTMxMDUwMzA3MDAwMFowgbQxCzAJBgNV  BAYTAlVTMRAwDgYDVQQIEwdBcml6b25hMRMwEQYDVQQHEwpTY290dHNkYWxlMRow  GAYDVQQKExFHb0RhZGR5LmNvbSwgSW5jLjEtMCsGA1UECxMkaHR0cDovL2NlcnRz  LmdvZGFkZHkuY29tL3JlcG9zaXRvcnkvMTMwMQYDVQQDEypHbyBEYWRkeSBTZWN1  cmUgQ2VydGlmaWNhdGUgQXV0aG9yaXR5IC0gRzIwggEiMA0GCSqGSIb3DQEBAQUA  A4IBDwAwggEKAoIBAQC54MsQ1K92vdSTYuswZLiBCGzDBNliF44v/z5lz4/OYuY8  UhzaFkVLVat4a2ODYpDOD2lsmcgaFItMzEUz6ojcnqOvK/6AYZ15V8TPLvQ/MDxd  R/yaFrzDN5ZBUY4RS1T4KL7QjL7wMDge87Am+GZHY23ecSZHjzhHU9FGHbTj3ADq  Ray9vHHZqm8A29vNMDp5T19MR/gd71vCxJ1gO7GyQ5HYpDNO6rPWJ0+tJYqlxvTV  0KaudAVkV4i1RFXULSo6Pvi4vekyCgKUZMQWOlDxSq7neTOvDCAHf+jfBDnCaQJs  Y1L6d8EbyHSHyLmTGFBUNUtpTrw700kuH9zB0lL7AgMBAAGjggEaMIIBFjAPBgNV  HRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBBjAdBgNVHQ4EFgQUQMK9J47MNIMw  ojPX+2yz8LQsgM4wHwYDVR0jBBgwFoAUOpqFBxBnKLbv9r0FQW4gwZTaD94wNAYI  KwYBBQUHAQEEKDAmMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5nb2RhZGR5LmNv  bS8wNQYDVR0fBC4wLDAqoCigJoYkaHR0cDovL2NybC5nb2RhZGR5LmNvbS9nZHJv  b3QtZzIuY3JsMEYGA1UdIAQ/MD0wOwYEVR0gADAzMDEGCCsGAQUFBwIBFiVodHRw  czovL2NlcnRzLmdvZGFkZHkuY29tL3JlcG9zaXRvcnkvMA0GCSqGSIb3DQEBCwUA  A4IBAQAIfmyTEMg4uJapkEv/oV9PBO9sPpyIBslQj6Zz91cxG7685C/b+LrTW+C0  5+Z5Yg4MotdqY3MxtfWoSKQ7CC2iXZDXtHwlTxFWMMS2RJ17LJ3lXubvDGGqv+Qq  G+6EnriDfcFDzkSnE3ANkR/0yBOtg2DZ2HKocyQetawiDsoXiWJYRBuriSUBAA/N  xBti21G00w9RKpv0vHP8ds42pM3Z2Czqrpv1KrKQ0U11GIo/ikGQI31bS/6kA1ib  RrLDYGCD+H1QQc7CoZDDu+8CL9IVVO5EFdkKrqeKM+2xLXY2JtwE65/3YR8V3Idv  7kaWKK2hJn0KCacuBKONvPi8BDABMIIGwjCCBaqgAwIBAgIIauE0hx6pkNYwDQYJ  KoZIhvcNAQELBQAwgbQxCzAJBgNVBAYTAlVTMRAwDgYDVQQIEwdBcml6b25hMRMw  EQYDVQQHEwpTY290dHNkYWxlMRowGAYDVQQKExFHb0RhZGR5LmNvbSwgSW5jLjEt  MCsGA1UECxMkaHR0cDovL2NlcnRzLmdvZGFkZHkuY29tL3JlcG9zaXRvcnkvMTMw  MQYDVQQDEypHbyBEYWRkeSBTZWN1cmUgQ2VydGlmaWNhdGUgQXV0aG9yaXR5IC0g  RzIwHhcNMjAwODIwMjEyMDE4WhcNMjIwODIwMjA0NTAxWjBBMSEwHwYDVQQLExhE  b21haW4gQ29udHJvbCBWYWxpZGF0ZWQxHDAaBgNVBAMMEyouY2VnZXBtb250cGV0  aXQuY2EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQD5Ltgk7dQyCHk9  fmRVqFWNLa+W1QB0zeVzrJ3t4aCzM/7c8HVpUZfopxCu1gMAcbHqOE3kiK0n5DqL  lbdeGiJ4fdqhTDKKeH6P6L0xATbcUBXWZ0iJROgml5Kc0oTv0gyimcnCKb4qjkFL  mbmtxdQYzcDO4uvmk+ro7Q2uxQrx4u13oXZKHjrENW2nxnLsiumTsyscmGnVT7b0  1V7Xj3+DWin2hNNnUosrVeoVGEvxVsNe8RpWMYJzbqeWJ/p2WQkiA+Bdev6uuCba  EUC2RfGMcupCQg1CErmitjQB5Giwszre9FeaPbuQAxpz+Zst8WGusumMcu7+kScF  fIuln9hRAgMBAAGjggNIMIIDRDAMBgNVHRMBAf8EAjAAMB0GA1UdJQQWMBQGCCsG  AQUFBwMBBggrBgEFBQcDAjAOBgNVHQ8BAf8EBAMCBaAwOAYDVR0fBDEwLzAtoCug  KYYnaHR0cDovL2NybC5nb2RhZGR5LmNvbS9nZGlnMnMxLTIyMzIuY3JsMF0GA1Ud  IARWMFQwSAYLYIZIAYb9bQEHFwEwOTA3BggrBgEFBQcCARYraHR0cDovL2NlcnRp  ZmljYXRlcy5nb2RhZGR5LmNvbS9yZXBvc2l0b3J5LzAIBgZngQwBAgEwdgYIKwYB  BQUHAQEEajBoMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5nb2RhZGR5LmNvbS8w  QAYIKwYBBQUHMAKGNGh0dHA6Ly9jZXJ0aWZpY2F0ZXMuZ29kYWRkeS5jb20vcmVw  b3NpdG9yeS9nZGlnMi5jcnQwHwYDVR0jBBgwFoAUQMK9J47MNIMwojPX+2yz8LQs  gM4wMQYDVR0RBCowKIITKi5jZWdlcG1vbnRwZXRpdC5jYYIRY2VnZXBtb250cGV0  aXQuY2EwHQYDVR0OBBYEFLQlVjLXe+CHtMensYEmIVATb+vZMIIBfwYKKwYBBAHW  eQIEAgSCAW8EggFrAWkAdwApeb7wnjk5IfBWc59jpXflvld9nGAK+PlNXSZcJV3H  hAAAAXQNvnQLAAAEAwBIMEYCIQCiUDYjTYv8/AIPs4DfneB1K2LrtwfBNf8knkUN  MahIAwIhANioIcxZM04ZUAp1+C3tW0YIjwm1HnwperrWZenqC7shAHYAIkVFB1lV  JFaWP6Ev8fdthuAjJmOtwEt/XcaDXG7iDwIAAAF0Db51zwAABAMARzBFAiEAwV0i  dGwbu+9fkmuiJOasu0XlfgQYEEF+9MlwtsmAbJYCIHnIbENI1HEHQRDVg9fei0rV  DKkAUE+IYdghkZmo843eAHYAQcjKsd8iRkoQxqE6CUKHXk4xixsD6+tLx2jwkGKW  BvYAAAF0Db525gAABAMARzBFAiAOVQAtb4k50df1kCgivUctOZJcsoeLgC3xMEjN  BqMCAgIhAOOrr8nYxv6zuAPVbssWUAZN+HQGfNB8sstPFXrTpWjeMA0GCSqGSIb3  DQEBCwUAA4IBAQBFP03qtcd4hNXr7ZvDvWjYCJoNmpisNvHjPN9Uwoz9XiTsNxB/  rFeiYU4j13bwUS3/JPijYd8t06iAMvdvaQ+QsUg/fry1riHXoHH3nZdQwX27vIYQ  W3zNOWFZWpNHiI4lSz7/crph/w8OQ6AWmBzNO+ZnKiDQp98iuaz91mEk8KUosIpT  qRjFOhrqMyWDKSRkVlOFrvf1RyRB2Yuey7GYAhZp2xGhuW4vjrudGpBT4VCNmv/+  33CuFEWYpy8OiBTJqUupX6+kbcejy+YxDNoKOeGwGZyrlX57W0JrEiZHKbIBEj27  BIzOf/4RahfWFd12HyRWklYTQR4F5nEQq7vzMYIB7TCCAekCAQEwgcEwgbQxCzAJ  BgNVBAYTAlVTMRAwDgYDVQQIEwdBcml6b25hMRMwEQYDVQQHEwpTY290dHNkYWxl  MRowGAYDVQQKExFHb0RhZGR5LmNvbSwgSW5jLjEtMCsGA1UECxMkaHR0cDovL2Nl  cnRzLmdvZGFkZHkuY29tL3JlcG9zaXRvcnkvMTMwMQYDVQQDEypHbyBEYWRkeSBT  ZWN1cmUgQ2VydGlmaWNhdGUgQXV0aG9yaXR5IC0gRzICCGrhNIceqZDWMA0GCWCG  SAFlAwQCAQUAMA0GCSqGSIb3DQEBAQUABIIBACg1pLBVu0SXIKPD8b4njXcs3Anq  JFn1YpyUdrjuNruobQGvOC0f4DURMDyFnGxVVREvkMICOmp/w8lEaD0RJQlakxiy  XYYvsAVBf5lqNeSN2B9OxFbqnWpike66csPruAX392YR0/5J3Djf7yv+EWA88i7t  2wQknTWFnN8WztI2wcMZBlPoXRcyw5NwRO9bSMcr65U9KpcCgRI2zuvykx8O6UqI  +Z+SIzCu5fu8SiCYSy+HogmZri3QU6BD50XrEcbM17KhQk0gjlMFjAbVHYwmnwiX  xQmfPIjXB2XcrbaPoFS9j7JTu+PfxwpOSbn3s1jifa4Ki36GHkGU27VZSMs=  
RDP;

header('Content-Type: application/x-rdp');
header("Content-Disposition: attachment; filename=\"Manuels de maintenance.rdp\"");
header('Cache-Control: private, no-store');
echo str_replace("\n", "\r\n", $rdp) . "\r\n";
